name: Ingest News

on:
  schedule:
    - cron: '*/30 * * * *'   # every 30 min (UTC)
  workflow_dispatch:

jobs:
  ingest:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: services/ingestor

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run ingestor
        env:
          # EITHER provide the full DSN in one secret:
          PG_DSN: ${{ secrets.PG_DSN }}

          # OR comment the line above and provide parts below:
          PGHOST: ${{ secrets.PGHOST }}
          PGPORT: ${{ secrets.PGPORT }}
          PGDATABASE: ${{ secrets.PGDATABASE }}
          PGUSER: ${{ secrets.PGUSER }}
          PGPASSWORD: ${{ secrets.PGPASSWORD }}
          PGSSLMODE: ${{ secrets.PGSSLMODE }}   # must be: require (no quotes)
          PGOPTIONS: project=${{ secrets.SUPABASE_PROJECT_REF }}  # needed for Supabase pooler
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_MODEL: gpt-4o-mini
        run: python ingest.py
