name: Ingest News

on:
  schedule:
    - cron: '0 * * * *'   # every hour (UTC)
  workflow_dispatch:

jobs:
  ingest:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services/ingestor

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run ingestor (hourly one-and-done)
        env:
          PG_DSN: ${{ secrets.PG_DSN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_MODEL: gpt-4o-mini
        run: python ingest.py

