# .github/workflows/ingest.yml
name: Ingest News

on:
  schedule:
    - cron: '*/30 * * * *'   # every 30 minutes (UTC)
  workflow_dispatch:        # run it manually

jobs:
  ingest:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services/ingestor  # <-- IMPORTANT
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run ingestor
        env:
          PG_DSN: ${{ secrets.PG_DSN }}              # from repo settings
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}  # not used by the hello-world, but keep it
          OPENAI_MODEL: gpt-4o-mini
        run: python ingest.py


